### ISSUE TITLE
Do simp

### ISSUE THREAD

**Issue by khoek** [semorrison/lean-tidy#10]
Hi Scott,

Would you be able to point me at where the old rewrite search used simp (and presumably extracted a proof along with it)? The last revision before the old searcher got ripped out is https://github.com/semorrison/lean-tidy/tree/9e021444a437e22f66f17318d734cbfb00cbca56, and I had a look in https://github.com/semorrison/lean-tidy/blob/9e021444a437e22f66f17318d734cbfb00cbca56/src/tidy/rewrite_search.lean and rewrite_all.lean to no avail.

Also, to hopefully decrease the barrier to you fully hooking-up to the rewrite_searcher without me explaining the last thing I've messed around with, I've ripped out the call to `rewrite_all` created https://github.com/khoek/lean-tidy/blob/071dd30b0ae280bb85f1f33583150b8e6dd59177/src/tidy/rewrite_search/core/hook.lean. This might have been a bit too heavy-handed, but I can just put it back-in if that turns out to be the case.

In the file there is a little blurb above `discover_more_rewrites` (the only function) about what its job is, but hopefully it's pretty self-explanatory. If the interface I present there is free-enough, and you don't want to wait for me, feel free to chuck in a call to your partial rewriter code replacing the two-line wrapper for the current `all_rewrites_list` implementation.

**Comment by khoek** [comment]
I think I did this in https://github.com/khoek/lean-tidy/commit/3e136c8e2b4a22484517fec6645a0795c1920673.

I'm not sure if what I did is useful though, I haven't got an example where the simp helps out, and it slows us down slightly.

**Comment by kim-em** [comment]
Ah, okay, I just found you the old version, but didn't see that you've
already done it.

https://github.com/semorrison/lean-tidy/blob/775079d0164288662e6a7f75f9315f3ea23f51ac/src/tidy/rewrite_search.lean#L377

I think it's good to have; I suspect that `dsimp` may be a useful step even
if `simp` turns out not to be. Once we're successfully following good
rewrites immediately, perhaps we can hook up `simp` or `dsimp` as "last
resorts".

best,
Scott
